export const JWT_VERIFICATION_TOKEN_SECRET = 'JWT_VERIFICATION_TOKEN_SECRET';
export const JWT_VERIFICATION_TOKEN_EXP_TIME =
  'JWT_VERIFICATION_TOKEN_EXP_TIME';
export const EMAIL_CONFIRMATION_URL = 'EMAIL_CONFIRMATION_URL'
